pub mod account_operations;
pub mod archive;
pub mod boostrapper_importer;
pub mod crush;
pub mod discord_rpc;
pub mod fs;
pub mod gbs_operations;
#[cfg(target_os = "macos")]
pub mod install_roblox_mac;
pub mod launch_roblox;
pub mod local_app_settings;
pub mod mods;
pub mod pre_processing;
pub mod process_roblox;
#[cfg(target_os = "windows")]
pub mod properity;
pub mod roblox_deployment;
#[cfg(target_os = "windows")]
pub mod shortcuts;

#[cfg(target_os = "macos")]
pub mod mac;
pub mod watcher;
pub mod window;
