<script lang="ts">
    import { onMount } from 'svelte'
    import { _ } from 'svelte-i18n'

    let text = $state('')
    let props = $props()

    onMount(() => {
        const items = [
            'Hello',
            'Have you ever tried getting your crush like you?',
            'roblox vn community rn:',
            'Hello everybody',
            'we are all slandering vng',
            'leventgameing is the GOAT',
            'eek!',
            'Loading malware....',
            'Deleting system32....',
            'I suppose',
            'Are you reading this yes?',
            'Say hi to the new miawuawua',
            'I have a crush but she didnt know it yet',
            "What's a high tier app look like to a low tier boostraper?",
            "Let's make crush mainstream",
            'meow',
            '100 cp fans vs happiness',
            'Everything but adding Server region selection to crush',
            '"I have crush, you are not"',
            'i am really sorry about that',
            'binary (10010100101) non-binary (HelloWorld"(Print)")',
            'im adding an injector next week',
            'successfully installed c++ on your machine',
            'you know what? i also installed c# on your machine!',
            "Having a dumb person around proved to expand expand a person's lifespan. Thanks for being here!",
            '🐘',
            'ily',
            'me updating 100 billons updates to crush',
            'if you cant sleep put on mommy amsr',
            'Join our community server!',
            "I've detected your homework folder over 10 TB, whats going on there?",
            'Big thanks for bratic for promoting crush',
            'ouh shii 👀👀',
            "You're cute lowk",
            'Have you ever have a dessert',
            'fym ouh shii 😭😭',
            'i know where you are',
            'collect my lost souls',
            'keep yourself safe',
            'i have food the other day its was good',
            'hi',
            '"Quick doctor help him!" " What is his type? " " He\'s into mommies " " ??? 😭😭 " ',
            'Tell your crush to use crush',
            '"claude know all my api keys"',
            'DM mally for daily instagram reels',
            'the factory must grow',
            'maybe we\'ll meet at a bar, we\'ll drive a funky euhhh',
            'crush can get smaller than a image',
            '"I wish an older woman groomed me when I was a teen maybe I wouldn’t be so awkward around women then"',
            'ALT + F4 for free robux',
            'local bars hate me when i pull this move',
            'duh',
            'This text can be funny sometimes',
            'Ocean Dih',
            'installing macos on a non-apple machine is hell',
            'a star on github is likey likey',
            'Think like an engineer',
            'i hope your day is better',
            'Thank you John C. Rush',
            'Im gonna murder all my mods',
            'Mally think he is tuff but im tuffer, Sigma sigma boy',
            'im gooning to find you bro',
            'go to sleep cute boy',
            'Can you build crush in build a boat?',
            '"eat poop" - 0xf9',
            'we may now kiss',
            'fuck you :3',
            'This is a fun fact',
            'Make lil crushies with your crush gng 💔🥀',
            "Crush started its development on March, 14 2026, 10 days after Mally's birthday!",
            'Shoutout to alexdahumbleone',
            'infinity update ahh',
            'stop larping python in your bio that is not tuff',
            "thanks for using crush bro you're so tuff",
            '"kernal cheats using python" 😭😭😭😭',
            'Something is coming in 3 days.',
            'what the fu-',
            'these text are mostly qouted from discord',
            'Thank you Mr John C. Rush thanks for you legacy',
            'they are calling',
            'You have 10+ messages pending.',
            'its so cool',
            'i WILL eat you',
            'This is crush!',
            'Hello gamers',
            'crush is now on macos',
            'BRO BE HATING ON ANYTHING 😭😭',
            'Also try out Bloxstrap',
            'Also try out Froststrap',
            'Also try out Voidstrap',
            'Also try out Fishstrap',
        ] as unknown as string[]
        if (Array.isArray(items) && items.length > 0) {
            text = items[Math.floor(Math.random() * items.length)]
        } else {
            text = $_('pages.choiceWin.funFacts.fallback')
        }
    })
</script>

<p class="text-sm text-gray-600 {props.class}">{text}</p>
