//! Safe Rust bindings for the SwiftTunnel SDK.
//!
//! Generated by claude.ai, i aint doing this shit
//!
//! # Setup
//!
//! In your `build.rs`:
//! ```rust
//! fn main() {
//!     println!("cargo:rustc-link-search=native=libs");
//!     println!("cargo:rustc-link-lib=dylib=swifttunnel");
//! }
//! ```
//!
//! Place `swifttunnel.dll` in a `libs/` folder next to `Cargo.toml`.
//!
//! # Usage
//!
//! ```rust
//! let sdk = SwiftTunnel::init().unwrap();
//! sdk.auth_sign_in("user@example.com", "hunter2").unwrap();
//! sdk.connect_ex(ConnectOptions {
//!     region: "singapore".into(),
//!     apps: vec!["game.exe".into()],
//!     auto_routing: Some(AutoRouting {
//!         enabled: true,
//!         whitelisted_regions: vec!["US East".into()],
//!     }),
//! }).unwrap();
//! ```

use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_int, c_void};

// ── Error constants ────────────────────────────────────────────────────────────

pub const SUCCESS: i32 = 0;
pub const ERROR_INVALID_PARAM: i32 = -1;
pub const ERROR_NOT_INITIALIZED: i32 = -2;
pub const ERROR_ALREADY_CONNECTED: i32 = -3;
pub const ERROR_NOT_CONNECTED: i32 = -4;
pub const ERROR_INTERNAL: i32 = -5;
pub const ERROR_AUTH: i32 = -6;
pub const ERROR_NETWORK: i32 = -7;
pub const ERROR_CONFIG: i32 = -8;
pub const ERROR_SPLIT_TUNNEL: i32 = -9;
pub const ERROR_VPN: i32 = -10;
pub const ERROR_USER_BANNED: i32 = -11;

// ── Raw FFI declarations ───────────────────────────────────────────────────────

#[link(name = "swifttunnel")]
extern "C" {
    fn swifttunnel_init() -> i32;
    fn swifttunnel_cleanup();
    fn swifttunnel_version() -> *mut c_char;
    fn swifttunnel_free_string(ptr: *mut c_char);

    fn swifttunnel_auth_sign_in(email: *const c_char, password: *const c_char) -> i32;
    fn swifttunnel_auth_start_oauth() -> *mut c_char;
    fn swifttunnel_auth_poll_oauth() -> i32;
    fn swifttunnel_auth_cancel_oauth();
    fn swifttunnel_auth_refresh() -> i32;
    fn swifttunnel_auth_sign_out();
    fn swifttunnel_auth_is_logged_in() -> i32;
    fn swifttunnel_auth_get_user_json() -> *mut c_char;

    fn swifttunnel_servers_fetch() -> i32;
    fn swifttunnel_servers_get_json() -> *mut c_char;
    fn swifttunnel_servers_ping(region: *const c_char) -> i32;

    fn swifttunnel_connect(region: *const c_char, apps_json: *const c_char) -> i32;
    fn swifttunnel_connect_ex(options_json: *const c_char) -> i32;
    fn swifttunnel_disconnect() -> i32;
    fn swifttunnel_get_state() -> i32;
    fn swifttunnel_get_state_json() -> *mut c_char;

    fn swifttunnel_get_tunneled_processes() -> *mut c_char;
    fn swifttunnel_get_stats_json() -> *mut c_char;
    fn swifttunnel_get_auto_routing_json() -> *mut c_char;
    fn swifttunnel_refresh_processes() -> i32;

    fn swifttunnel_on_state_change(cb: extern "C" fn(i32, *mut c_void), ctx: *mut c_void);
    fn swifttunnel_on_error(cb: extern "C" fn(i32, *const i8, *mut c_void), ctx: *mut c_void);
    fn swifttunnel_on_process_detected(
        cb: extern "C" fn(*const i8, i32, *mut c_void),
        ctx: *mut c_void,
    );
    fn swifttunnel_on_auto_routing_event(
        cb: extern "C" fn(*const i8, *mut c_void),
        ctx: *mut c_void,
    );

    fn swifttunnel_get_last_error() -> *mut c_char;
    fn swifttunnel_get_last_error_code() -> i32;
    fn swifttunnel_clear_error();
}

// ── SDK error type ─────────────────────────────────────────────────────────────

#[derive(Debug)]
pub struct SdkError {
    pub code: i32,
    pub message: String,
}

impl std::fmt::Display for SdkError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "SwiftTunnel error {}: {}", self.code, self.message)
    }
}

impl std::error::Error for SdkError {}

pub type Result<T> = std::result::Result<T, SdkError>;

// ── Connection state ───────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConnectionState {
    Disconnected,
    FetchingConfig,
    Connecting,
    ConfiguringSplitTunnel,
    Connected,
    Disconnecting,
    Error,
    NotInitialized,
    Unknown(i32),
}

impl From<i32> for ConnectionState {
    fn from(code: i32) -> Self {
        match code {
            0 => Self::Disconnected,
            1 => Self::FetchingConfig,
            2 => Self::Connecting,
            3 => Self::ConfiguringSplitTunnel,
            4 => Self::Connected,
            5 => Self::Disconnecting,
            -1 => Self::Error,
            -2 => Self::NotInitialized,
            n => Self::Unknown(n),
        }
    }
}

// ── OAuth poll result ──────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OAuthPoll {
    Complete,
    Waiting,
    Error,
}

impl From<i32> for OAuthPoll {
    fn from(v: i32) -> Self {
        match v {
            1 => Self::Complete,
            0 => Self::Waiting,
            _ => Self::Error,
        }
    }
}

// ── connect_ex option types ────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct AutoRouting {
    pub enabled: bool,
    pub whitelisted_regions: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct ConnectOptions {
    pub region: String,
    pub apps: Vec<String>,
    pub auto_routing: Option<AutoRouting>,
    /// Override the relay endpoint (disables auto-routing when set).
    pub custom_relay_server: Option<String>,
    /// Per-region forced server overrides: `{ "region_id": "server_id" }`.
    pub forced_servers: std::collections::HashMap<String, String>,
    /// Roblox Route Assist: tunnel Roblox TCP API/bootstrap traffic and repair
    /// its bootstrap DNS. Helps bypass network/country bans and improves the
    /// odds Roblox places the player near the tunneled region.
    pub enable_api_tunneling: bool,
}

impl Default for ConnectOptions {
    fn default() -> Self {
        Self {
            region: String::new(),
            apps: Vec::new(),
            auto_routing: None,
            custom_relay_server: None,
            forced_servers: std::collections::HashMap::new(),
            enable_api_tunneling: false,
        }
    }
}

impl ConnectOptions {
    fn to_json(&self) -> String {
        let apps: String = self
            .apps
            .iter()
            .map(|a| format!("\"{}\"", escape_json_str(a)))
            .collect::<Vec<_>>()
            .join(",");

        let ar = match &self.auto_routing {
            Some(ar) => {
                let regions: String = ar
                    .whitelisted_regions
                    .iter()
                    .map(|r| format!("\"{}\"", escape_json_str(r)))
                    .collect::<Vec<_>>()
                    .join(",");
                format!(
                    ",\"auto_routing\":{{\"enabled\":{},\"whitelisted_regions\":[{}]}}",
                    ar.enabled, regions
                )
            }
            None => String::new(),
        };

        let custom_relay = match &self.custom_relay_server {
            Some(s) => format!(",\"custom_relay_server\":\"{}\"", escape_json_str(s)),
            None => String::new(),
        };

        let forced: String = self
            .forced_servers
            .iter()
            .map(|(k, v)| format!("\"{}\":\"{}\"", escape_json_str(k), escape_json_str(v)))
            .collect::<Vec<_>>()
            .join(",");
        let forced_servers = format!(",\"forced_servers\":{{{}}}", forced);

        let route_assist = format!(",\"enable_api_tunneling\":{}", self.enable_api_tunneling);

        format!(
            "{{\"region\":\"{}\",\"apps\":[{}]{}{}{}{}}}",
            escape_json_str(&self.region),
            apps,
            ar,
            custom_relay,
            forced_servers,
            route_assist,
        )
    }
}

// ── Parsed JSON types ──────────────────────────────────────────────────────────

/// Parsed user info from `swifttunnel_auth_get_user_json`.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct UserInfo {
    pub id: String,
    pub email: String,
    #[serde(default)]
    pub is_tester: bool,
    #[serde(default)]
    pub is_banned: bool,
    #[serde(default)]
    pub banned_reason: Option<String>,
    #[serde(default)]
    pub banned_at: Option<String>,
}

/// Parsed connected state from `swifttunnel_get_state_json` when `state == "Connected"`.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ConnectedStateInfo {
    pub region: String,
    pub endpoint: String,
    pub assigned_ip: String,
    pub relay_auth_mode: String,
    pub split_tunnel_active: bool,
    pub tunneled_processes: Vec<String>,
    /// None = healthy, "stale" = no traffic 30 s+, "dead" = no response 60 s+
    pub relay_status: Option<String>,
}

// ── Internal helpers ───────────────────────────────────────────────────────────

/// Escape special characters for embedding a value inside a JSON string literal.
fn escape_json_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Take ownership of a SDK-allocated string and free it.
unsafe fn take_sdk_string(ptr: *mut c_char) -> Option<String> {
    if ptr.is_null() {
        return None;
    }
    let s = CStr::from_ptr(ptr).to_string_lossy().into_owned();
    swifttunnel_free_string(ptr);
    Some(s)
}

fn cstring(s: &str) -> CString {
    CString::new(s).unwrap_or_else(|_| CString::new("").unwrap())
}

// ── Main SDK handle ────────────────────────────────────────────────────────────

/// Safe handle to the SwiftTunnel SDK.
/// Calls `swifttunnel_cleanup()` automatically on drop.
pub struct SwiftTunnel;

impl SwiftTunnel {
    // ── Core ──────────────────────────────────────────────────────────────────

    /// Initialise the SDK. Call once at startup.
    pub fn init() -> Result<Self> {
        let rc = unsafe { swifttunnel_init() };
        if rc == SUCCESS {
            Ok(SwiftTunnel)
        } else {
            Err(SdkError {
                code: rc,
                message: "SDK init failed".into(),
            })
        }
    }

    /// Return the SDK version string.
    pub fn version(&self) -> String {
        unsafe { take_sdk_string(swifttunnel_version()) }.unwrap_or_else(|| "<unknown>".into())
    }

    // ── Authentication ────────────────────────────────────────────────────────

    /// Sign in with email and password.
    pub fn auth_sign_in(&self, email: &str, password: &str) -> Result<()> {
        let e = cstring(email);
        let p = cstring(password);
        let rc = unsafe { swifttunnel_auth_sign_in(e.as_ptr(), p.as_ptr()) };
        self.ok(rc)
    }

    /// Start Google OAuth. Returns the URL to open in a browser.
    pub fn auth_start_oauth(&self) -> Result<String> {
        let ptr = unsafe { swifttunnel_auth_start_oauth() };
        unsafe { take_sdk_string(ptr) }
            .ok_or_else(|| self.last_error_or("OAuth start returned null"))
    }

    /// Poll for OAuth completion.
    pub fn auth_poll_oauth(&self) -> OAuthPoll {
        OAuthPoll::from(unsafe { swifttunnel_auth_poll_oauth() })
    }

    /// Cancel an in-progress OAuth flow.
    pub fn auth_cancel_oauth(&self) {
        unsafe { swifttunnel_auth_cancel_oauth() }
    }

    /// Refresh the access token.
    pub fn auth_refresh(&self) -> Result<()> {
        self.ok(unsafe { swifttunnel_auth_refresh() })
    }

    /// Sign out and clear stored credentials.
    pub fn auth_sign_out(&self) {
        unsafe { swifttunnel_auth_sign_out() }
    }

    /// Returns `true` if a user is currently logged in.
    pub fn auth_is_logged_in(&self) -> bool {
        unsafe { swifttunnel_auth_is_logged_in() == 1 }
    }

    /// Get user info as a raw JSON string.
    /// Returns `None` if not logged in.
    ///
    /// JSON shape: `{"id":"...","email":"...","is_tester":false,"is_banned":false,"banned_reason":null,"banned_at":null}`
    pub fn auth_get_user_json(&self) -> Option<String> {
        unsafe { take_sdk_string(swifttunnel_auth_get_user_json()) }
    }

    /// Get user info parsed into a [`UserInfo`] struct.
    /// Returns `None` if not logged in or parsing fails.
    pub fn auth_get_user(&self) -> Option<UserInfo> {
        let json = self.auth_get_user_json()?;
        serde_json::from_str(&json).ok()
    }

    // ── Servers ───────────────────────────────────────────────────────────────

    /// Fetch the server list from the API.
    pub fn servers_fetch(&self) -> Result<()> {
        self.ok(unsafe { swifttunnel_servers_fetch() })
    }

    /// Get the cached server list as JSON (`{"servers":[...],"regions":[...]}`).
    pub fn servers_get_json(&self) -> Option<String> {
        unsafe { take_sdk_string(swifttunnel_servers_get_json()) }
    }

    /// Ping a region and return latency in ms. Returns `Err` on failure.
    pub fn servers_ping(&self, region: &str) -> Result<u32> {
        let r = cstring(region);
        let ms = unsafe { swifttunnel_servers_ping(r.as_ptr()) };
        if ms >= 0 {
            Ok(ms as u32)
        } else {
            Err(self.last_error_or("ping failed"))
        }
    }

    // ── Connection ────────────────────────────────────────────────────────────

    /// Connect using full options (preferred).
    pub fn connect_ex(&self, opts: ConnectOptions) -> Result<()> {
        let json = cstring(&opts.to_json());
        self.ok(unsafe { swifttunnel_connect_ex(json.as_ptr()) })
    }

    /// Legacy connect (auto-routing disabled).
    /// `apps` is a JSON array string e.g. `["game.exe"]`.
    pub fn connect(&self, region: &str, apps_json: &str) -> Result<()> {
        let r = cstring(region);
        let a = cstring(apps_json);
        self.ok(unsafe { swifttunnel_connect(r.as_ptr(), a.as_ptr()) })
    }

    /// Disconnect from the VPN.
    pub fn disconnect(&self) -> Result<()> {
        self.ok(unsafe { swifttunnel_disconnect() })
    }

    /// Get the current connection state.
    pub fn get_state(&self) -> ConnectionState {
        ConnectionState::from(unsafe { swifttunnel_get_state() })
    }

    /// Get detailed connection state as JSON.
    ///
    /// When connected the JSON includes `assigned_ip`, `relay_auth_mode`, and `relay_status`.
    pub fn get_state_json(&self) -> Option<String> {
        unsafe { take_sdk_string(swifttunnel_get_state_json()) }
    }

    /// Get the connected-state details parsed into a [`ConnectedStateInfo`] struct.
    /// Returns `None` if not connected or parsing fails.
    pub fn get_connected_state(&self) -> Option<ConnectedStateInfo> {
        let json = self.get_state_json()?;
        let v: serde_json::Value = serde_json::from_str(&json).ok()?;
        if v.get("state")?.as_str()? != "Connected" {
            return None;
        }
        serde_json::from_value(v).ok()
    }

    // ── Split tunnel / stats ──────────────────────────────────────────────────

    /// Get currently tunnelled process names as a JSON array.
    pub fn get_tunneled_processes(&self) -> Option<String> {
        unsafe { take_sdk_string(swifttunnel_get_tunneled_processes()) }
    }

    /// Get relay packet statistics as JSON (`{"packets_sent":N,"packets_recv":N}`).
    pub fn get_stats_json(&self) -> Option<String> {
        unsafe { take_sdk_string(swifttunnel_get_stats_json()) }
    }

    /// Get auto-routing state as JSON.
    pub fn get_auto_routing_json(&self) -> Option<String> {
        unsafe { take_sdk_string(swifttunnel_get_auto_routing_json()) }
    }

    /// Trigger a re-scan of tunnelled processes.
    pub fn refresh_processes(&self) -> Result<()> {
        self.ok(unsafe { swifttunnel_refresh_processes() })
    }

    // ── Callbacks ─────────────────────────────────────────────────────────────

    /// Register a state-change callback.
    ///
    /// # Safety
    /// `ctx` must remain valid for the lifetime of the SDK.
    pub unsafe fn on_state_change(
        &self,
        cb: extern "C" fn(state_code: i32, ctx: *mut c_void),
        ctx: *mut c_void,
    ) {
        swifttunnel_on_state_change(cb, ctx);
    }

    /// Register an error callback.
    ///
    /// # Safety
    /// `ctx` must remain valid for the lifetime of the SDK.
    pub unsafe fn on_error(
        &self,
        cb: extern "C" fn(code: i32, message: *const i8, ctx: *mut c_void),
        ctx: *mut c_void,
    ) {
        swifttunnel_on_error(cb, ctx);
    }

    /// Register a process-detection callback.
    ///
    /// # Safety
    /// `ctx` must remain valid for the lifetime of the SDK.
    pub unsafe fn on_process_detected(
        &self,
        cb: extern "C" fn(process_name: *const i8, added: i32, ctx: *mut c_void),
        ctx: *mut c_void,
    ) {
        swifttunnel_on_process_detected(cb, ctx);
    }

    /// Register an auto-routing event callback. `event_json` is a JSON string.
    ///
    /// # Safety
    /// `ctx` must remain valid for the lifetime of the SDK.
    pub unsafe fn on_auto_routing_event(
        &self,
        cb: extern "C" fn(event_json: *const i8, ctx: *mut c_void),
        ctx: *mut c_void,
    ) {
        swifttunnel_on_auto_routing_event(cb, ctx);
    }

    // ── Error helpers ─────────────────────────────────────────────────────────

    /// Get the last error message (if any).
    pub fn get_last_error(&self) -> Option<String> {
        unsafe { take_sdk_string(swifttunnel_get_last_error()) }
    }

    /// Get the last error code (`SUCCESS` = 0 means no error).
    pub fn get_last_error_code(&self) -> i32 {
        unsafe { swifttunnel_get_last_error_code() }
    }

    /// Clear stored error state.
    pub fn clear_error(&self) {
        unsafe { swifttunnel_clear_error() }
    }

    // ── Internal ──────────────────────────────────────────────────────────────

    fn ok(&self, rc: i32) -> Result<()> {
        if rc == SUCCESS {
            Ok(())
        } else {
            Err(self.last_error_or("Unknown error"))
        }
    }

    fn last_error_or(&self, fallback: &str) -> SdkError {
        let code = unsafe { swifttunnel_get_last_error_code() };
        let message = unsafe { take_sdk_string(swifttunnel_get_last_error()) }
            .unwrap_or_else(|| fallback.into());
        SdkError { code, message }
    }
}

impl Drop for SwiftTunnel {
    fn drop(&mut self) {
        unsafe { swifttunnel_cleanup() }
    }
}
