name: goodcode

on:
    push:
        branches: [master]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2
  
            - name: Install Node
              uses: actions/setup-node@v6
              with:
                  node-version: 20

            - name: Install deps
              run: bun install

            - name: Type check
              run: bun run check

            - name: Rust checks
              working-directory: ./src-tauri
              run: |
                  cargo fmt -- --check
                  cargo clippy -- -D warnings

            - name: Build
              env:
                  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
              run: bun tauri build
