name: Tauri CI Build
on:
    pull_request:
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        if: github.head_ref != 'l10n_crowdin_translations'
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: 20
            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Cache Rust
              uses: Swatinem/rust-cache@v2
            - name: Install frontend deps
              run: bun install
            - name: Build Tauri
              env:
                TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
              run: bun tauri build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: tauri-windows-build
                  path: |
                      src-tauri/target/release/bundle/msi/*.msi
                      src-tauri/target/release/bundle/nsis/*.exe
